### ISSUE TITLE
What does the 'forward' mean in split_traintest.py?

### ISSUE THREAD

**Issue by abbyxxn** [YurongYou/Hindsight#1]
I have a question on the 'forward' in split_traintest.py under which circumstances would it be true?
`forward = origin_pose[0,:3] @ poses[seq_id][min_dist_indices][0, :3] > 0`

**Comment by YurongYou** [comment]
Hi! Thanks for your interest! This line is to determine if the ego car is moving in the same direction as it was in the reference sequence.
