### ISSUE TITLE
ValueError: cannot reshape array of size 265728 into shape (5)

### ISSUE THREAD

**Issue by BiaoBiaoLi** [YurongYou/Hindsight#2]
Thanks your work! when Download Lyft dataset and convert it to KITTI format, i meet this problem:
 File "/home/biaoli/anaconda3/envs/hindsight/lib/python3.8/site-packages/lyft_dataset_sdk/utils/data_classes.py", line 283, in from_file
    points = scan.reshape((-1, 5))[:, : cls.nbr_dims()]
ValueError: cannot reshape array of size 265728 into shape (5)
 24%|█████████▏                            | 5471/22680 [03:31<11:04, 25.90it/s]
is this a properly solution ?
https://github.com/lyft/nuscenes-devkit/issues/89
thanks you !

**Comment by YurongYou** [comment]
Hi BiaoBiaoLi! Thanks for your interest!
It seems I did not encounter this issue, but the solution you post should be proper (also see https://www.kaggle.com/c/3d-object-detection-for-autonomous-vehicles/discussion/110000).

**Comment by YurongYou** [comment]
I double-checked the data I used, and I found did patch the bin file before but forgot to include this step in the doc. Thanks for reporting it and I just updated the doc :)
