### ISSUE TITLE
Split NuScenes evaluation into groups using distance toward LiDAR

### ISSUE THREAD

**Issue by quan-dao** [YurongYou/Hindsight#3]
Hello,
Thank you very much for making your work available.
Can you share how to split NuScenes evaluation results into groups using distance toward LiDAR as you did in Table. 2 of your paper?

**Comment by YurongYou** [comment]
Hi quan-dao! We converted the nuScenes dataset into KITTI format and evaluated it using the same KITTI evaluation code.

**Comment by quan-dao** [comment]
Thank you.
